version: "3"
build:
  context: ./DockerData/
  image: eewp
  args:
    buildno: 1

services:
  database:
    container_name: database
    image: mariadb
    ports:
      - 3306:3306
    volumes: 
      - ./DockerData/mysql:/var/lib/mysql
      - ./DockerData/ee.sql:/docker-entrypoint-initdb.d/init-ee.sql
    env_file:
      - ./DockerData/db.env